server.port: 8000
reserversion.claim.allocated.time: 900

spring:
  tomcat:
      max-wait: 10000
      max-active: 5
      test-on-borrow: true
  main:
    banner-mode: "off"
    
spring.jpa.generate-ddl: true
spring.jpa.hibernate.ddl-auto: update
spring.datasource.initialization-mode: always
spring.datasource.platform: postgres
spring.datasource.url: jdbc:postgresql://localhost:5432/parking-management-system-db
spring.datasource.username: postgres
spring.datasource.password: warlord

stripe.secret.key: sk_test_51HskSzKjGxGlZ0lyFGqgqRioYYAOyxfjkJf1LPNvhQ1WPgbyRJ8P3rbpGpHJG0cJproPUd3jgpuT4JBlBb8nowwU00i38BUUCn
stripe.publishable.key: pk_test_51HskSzKjGxGlZ0ly9rb5ZXdHsozaY8DPqliYzVgOXhNvN6rtKUrRPM9lSH5WhzZUO79TNNIll80m7FjsYw0ZDY8D00lhUZjT52
