server.port: 8000
reservation.claim.allocated.time: 900

spring:
  tomcat:
    max-wait: 10000
    max-active: 5
    test-on-borrow: true
  main:
    banner-mode: "off"
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/parking-management-system
    username: postgres
    password: warlord


stripe:
  secret:
    key: sk_test_51HskSzKjGxGlZ0lyFGqgqRioYYAOyxfjkJf1LPNvhQ1WPgbyRJ8P3rbpGpHJG0cJproPUd3jgpuT4JBlBb8nowwU00i38BUUCn
  publishable:
    key: pk_test_51HskSzKjGxGlZ0ly9rb5ZXdHsozaY8DPqliYzVgOXhNvN6rtKUrRPM9lSH5WhzZUO79TNNIll80m7FjsYw0ZDY8D00lhUZjT52
#logging.level.org.springframework.jdbc.core.JdbcTemplate: DEBUG
#logging.level.org.springframework.jdbc.core.StatementCreatorUtils: TRACE
#logging.level.org.hibernate.SQL: DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE