server.port: 8000
reservation.claim.allocated.time: 900

spring:
  tomcat:
    max-wait: 10000
    max-active: 5
    test-on-borrow: true
  main:
    banner-mode: "off"
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/parking-management-system
    username: postgres
    password: warlord


stripe:
  secret:
    key: ${STRIPE_SECRET_KEY}
  publishable:
    key: ${STRIPE_PUBLISHABLE_KEY}
#logging.level.org.springframework.jdbc.core.JdbcTemplate: DEBUG
#logging.level.org.springframework.jdbc.core.StatementCreatorUtils: TRACE
#logging.level.org.hibernate.SQL: DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE